INSERT INTO student (name)
VALUES ('AASHIK H'),
    ('AASHIQ AHAMED N'),
    ('ABDUL BASHITH J'),
    ('ABDUL SALAM M'),
    ('ABISHEK KUMAR S'),
    ('AHMED ASLAM M'),
    ('AKSHAY PRASHAD M K'),
    ('AKUL PRADEEP'),
    ('AMARNATH A'),
    ('ANEESA BEGUM J'),
    ('ARSHATH FARWYZ S'),
    ('DEEPIKA K'),
    ('DHOWFEEK HASAN S'),
    ('FARHAN M'),
    ('GANESH U'),
    ('GULNAAZ BEGUM G'),
    ('HARINI SRI B'),
    ('IRSHAD YASSEEN A'),
    ('JANANI SRUTHIKA P'),
    ('JANANYA HARSHNI P S'),
    ('KAMAL V'),
    ('LEECHITA G'),
    ('MOHAMMED HAMDAN M'),
    ('MADHUNISHA M'),
    ('MAGESHWARAN S'),
    ('MOHAMED AABIDH A'),
    ('MOHAMED ARSHATH A'),
    ('MOHAMED ASIF M'),
    ('MOHAMED FAHEEM A'),
    ('MOHAMED FAIZ'),
    ('MOHAMED FARAAZMAN BIN FAROOQ S'),
    ('MOHAMED FOUZAN AYUBI K'),
    ('MOHAMED IRFAN S'),
    ('MOHAMED MAFAZ'),
    ('MOHAMED NASAR L'),
    ('MOHAMED NOWFAL M'),
    ('MOHAMED SAKEEL A'),
    ('MOHAMMED ASLAM A'),
    ('MUAATH LATHEEF J'),
    ('MUGUNTHAN K'),
    ('MUHAMMED RUHAAN C'),
    ('NASEERUDDEEN S'),
    ('NOORUL HASSAN'),
    ('PARTHIBAN K R'),
    ('PRIYANKA R'),
    ('RASITH NOVFAL S'),
    ('SHAFI ABDULLAH JAMEEL S'),
    ('SHAHNAZ H'),
    ('SOBITHA S'),
    ('SYED MOHAMMAD SHOAIB'),
    ('SYED SAMIULLAH'),
    ('SYED YAHEYA S.I'),
    ('TEJESHWAR K'),
    ('THALIB ZAFIR S'),
    ('UMAPATHY S'),
    ('VIGNESH N'),
    ('YAHIYA V'),
    ('YOGESH S'),
    ('YOOSUF RIFAI R'),
    ('ASHIQ AHAMED S'),
    ('JAYANDRAN S'),
    ('SAMEER MUSTAQ S'),
    ('SEAN SAMYUKT JOHNSON'),
    ('SURIYA B');
--
INSERT INTO subject (name)
VALUES ('Distributed Computing'),
    ('Emotional Intelligence'),
    ('Compuuter Vision');
